version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout

      - run:
          name: Create env file for build
          command: |
            touch .env

      - run:
          name: Build Docker image
          command: |
            echo "Building Docker image..."
            docker compose build

      - run:
          name: Verify image exists
          command: |
            docker compose images

  deploy:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:up+RAgJy8I7UOdzlO17YgnCc9QS79jffVvRHLm3UIno"

      - run:
          name: Deploy to AWS EC2
          command: |
            echo "Conectando a EC2 y desplegando..."
            ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_IP} "cd ${EC2_PATH} && git pull origin main && docker compose up --build -d && docker image prune -f && echo 'Deploy completado exitosamente en ${EC2_IP}'"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
